# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170722_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_visible',
            field=models.BooleanField(default=False),
        ),
    ]
