# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170722_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Keuze', 'verbose_name_plural': 'Keuzes'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Stemming', 'verbose_name_plural': 'Stemmingen'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_open',
            field=models.BooleanField(default=False, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_visible',
            field=models.BooleanField(default=False, verbose_name='Zichtbaar'),
        ),
    ]
