# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170722_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=2000, verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=2000, verbose_name='Tekst'),
        ),
    ]
